language: php

php:
    - 5.3
    - 5.4
    - 5.5

matrix:
    allow_failures:
        - php: 5.5

branches:
    except:
        - experimental

before_script:
    - composer install

script: phpunit --coverage-text -c app/
